2014-08-07 14:17:37,808 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:17:37,822 [ERROR] - [gsarpc] [SERVER_ERROR] An error in the client/server connection (must be string or read-only buffer, not list)
2014-08-07 14:17:37,830 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 49, in create
    return self._slice_authority_resource_manager.create_slice(certificate, credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/osliceauthorityrm/osliceauthorityresourcemanager.py", line 119, in create_slice
    root = ET.fromstring(credentials)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1641, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not list

2014-08-07 14:17:37,840 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:17:37,841 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Field {SLICE_NAME : True} is not of type STRING)
2014-08-07 14:17:37,841 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 47, in create
    self._delegate_tools.object_consistency_check(type_, fields)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 373, in object_consistency_check
    raise GFedv2ArgumentError('Field {' + key + ' : ' + str(value) + '} is not of type ' + field_type)
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Field {SLICE_NAME : True} is not of type STRING)

2014-08-07 14:17:37,851 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:17:37,862 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:37,862 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Member key to modify not of required type. Offending key is: PROJECT_MEMBER. Should be one of these types: ['SLICE_MEMBER', 'SLICE_ROLE'])
2014-08-07 14:17:37,863 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 122, in modify_membership
    result = self._delegate.modify_membership(type_, urn, self.requestCertificate(), credentials, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 158, in modify_membership
    self._delegate_tools.member_check(['SLICE_MEMBER', 'SLICE_ROLE'],options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 295, in member_check
    str(required_field_keys))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Member key to modify not of required type. Offending key is: PROJECT_MEMBER. Should be one of these types: ['SLICE_MEMBER', 'SLICE_ROLE'])

2014-08-07 14:17:37,872 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:17:37,886 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:17:37,898 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:17:37,912 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:17:37,921 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:17:37,931 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:37,948 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:17:37,957 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:37,967 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:17:37,976 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:37,985 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:17:37,996 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,005 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:17:38,014 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,023 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:17:38,034 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,046 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:17:38,056 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:17:38,065 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:17:38,066 [ERROR] - [gsarpc] [SERVER_ERROR] An error in the client/server connection (must be string or read-only buffer, not list)
2014-08-07 14:17:38,066 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 49, in create
    return self._slice_authority_resource_manager.create_slice(certificate, credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/osliceauthorityrm/osliceauthorityresourcemanager.py", line 119, in create_slice
    root = ET.fromstring(credentials)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1641, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not list

2014-08-07 14:17:38,074 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,096 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:17:38,106 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,116 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:17:38,126 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,135 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:17:38,144 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,155 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:17:38,164 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,173 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:17:38,184 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:17:38,193 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:17:38,201 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:17:38,213 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:17:38,222 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:17:38,232 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:17:38,241 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:17:38,251 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:17:38,264 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:17:38,266 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Invalid expiry date for object type: PROJECT)
2014-08-07 14:17:38,266 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 79, in update
    result = self._delegate.update(type_, urn, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 105, in update
    raise gfed_ex.GFedv2ArgumentError("Invalid expiry date for object type: " + str(type_))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Invalid expiry date for object type: PROJECT)

2014-08-07 14:17:38,279 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:17:38,555 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:17:38,564 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:17:38,577 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:17:38,577 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when updating an object : PROJECT_NAME)
2014-08-07 14:17:38,578 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 79, in update
    result = self._delegate.update(type_, urn, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 107, in update
    self._delegate_tools.object_update_check(fields, self._project_whitelist)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 346, in object_update_check
    raise GFedv2ArgumentError('Cannot pass the following key(s) when updating an object : ' + ', '.join(whitelist))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when updating an object : PROJECT_NAME)

2014-08-07 14:17:38,587 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:17:38,597 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:08,379 [INFO] - [gmarpc] Called: <get_version>
2014-08-07 14:25:08,395 [INFO] - [gmarpc] Called: <create>
2014-08-07 14:25:08,395 [ERROR] - [gmarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when creating an object : KEY_ID)
2014-08-07 14:25:08,416 [ERROR] - [gmarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gmavtwo.py", line 61, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/omavtwodelegate.py", line 45, in create
    self._delegate_tools.object_creation_check(fields, self._key_whitelist)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 328, in object_creation_check
    ', '.join(whitelist))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when creating an object : KEY_ID)

2014-08-07 14:25:08,423 [INFO] - [gmarpc] Called: <get_version>
2014-08-07 14:25:08,440 [INFO] - [gmarpc] Called: <create>
2014-08-07 14:25:08,472 [INFO] - [gmarpc] Called: <update>
2014-08-07 14:25:08,485 [INFO] - [gmarpc] Called: <lookup>
2014-08-07 14:25:08,500 [INFO] - [gmarpc] Called: <delete>
2014-08-07 14:25:08,513 [INFO] - [gmarpc] Called: <lookup>
2014-08-07 14:25:08,525 [INFO] - [gmarpc] Called: <create>
2014-08-07 14:25:08,525 [ERROR] - [gmarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Field {KEY_MEMBER : True} is not of type URN)
2014-08-07 14:25:08,525 [ERROR] - [gmarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gmavtwo.py", line 61, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/omavtwodelegate.py", line 46, in create
    self._delegate_tools.object_consistency_check(type_, fields)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 373, in object_consistency_check
    raise GFedv2ArgumentError('Field {' + key + ' : ' + str(value) + '} is not of type ' + field_type)
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Field {KEY_MEMBER : True} is not of type URN)

2014-08-07 14:25:08,535 [INFO] - [gmarpc] Called: <create>
2014-08-07 14:25:08,545 [INFO] - [gmarpc] Called: <update>
2014-08-07 14:25:08,545 [ERROR] - [gmarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when updating an object : KEY_TYPE)
2014-08-07 14:25:08,546 [ERROR] - [gmarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gmavtwo.py", line 77, in update
    result = self._delegate.update(type_, urn, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/omavtwodelegate.py", line 62, in update
    self._delegate_tools.object_update_check(fields, self._key_whitelist)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 346, in object_update_check
    raise GFedv2ArgumentError('Cannot pass the following key(s) when updating an object : ' + ', '.join(whitelist))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when updating an object : KEY_TYPE)

2014-08-07 14:25:08,554 [INFO] - [gmarpc] Called: <delete>
2014-08-07 14:25:08,563 [INFO] - [gmarpc] Called: <lookup>
2014-08-07 14:25:23,398 [INFO] - [gregistryrpc] Called: <get_trust_roots>
2014-08-07 14:25:23,408 [INFO] - [gregistryrpc] Called: <get_version>
2014-08-07 14:25:23,420 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,433 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,444 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,453 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,463 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,471 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,479 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,488 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,495 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,506 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,516 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,528 [INFO] - [gregistryrpc] Called: <lookup>
2014-08-07 14:25:23,537 [INFO] - [gregistryrpc] Called: <lookup_authorities_for_urns>
2014-08-07 14:25:30,757 [INFO] - [gsarpc] Called: <get_version>
2014-08-07 14:25:30,775 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:30,776 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when creating an object : SLICE_EXPIRED)
2014-08-07 14:25:30,776 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 46, in create
    self._delegate_tools.object_creation_check(fields, self._slice_whitelist)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 328, in object_creation_check
    ', '.join(whitelist))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when creating an object : SLICE_EXPIRED)

2014-08-07 14:25:30,785 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:30,803 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:30,888 [ERROR] - [gsarpc] [DUPLICATE_ERROR] An error indicating attempt to create an object that already exists (insertDocument :: caused by :: 11000 E11000 duplicate key error index: ohouse.sa.$PROJECT_URN_1  dup key: { : "urn:publicid+IDN+0.0.0.0+project+TEST-SLICE-CREDENTIALS" })
2014-08-07 14:25:30,906 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 57, in create
    return self._slice_authority_resource_manager.create_project(certificate, credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/osliceauthorityrm/osliceauthorityresourcemanager.py", line 209, in create_project
    return self._resource_manager_tools.object_create(self.AUTHORITY_NAME, fields, 'project')
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/resourcemanagertools.py", line 133, in object_create
    raise GFedv2DuplicateError(str(e))
GFedv2DuplicateError: [DUPLICATE_ERROR] An error indicating attempt to create an object that already exists (insertDocument :: caused by :: 11000 E11000 duplicate key error index: ohouse.sa.$PROJECT_URN_1  dup key: { : "urn:publicid+IDN+0.0.0.0+project+TEST-SLICE-CREDENTIALS" })

2014-08-07 14:25:30,915 [INFO] - [gsarpc] Called: <get_version>
2014-08-07 14:25:30,931 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:30,932 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:30,932 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:30,941 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:30,952 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:30,952 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:30,953 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:30,962 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:30,971 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:30,971 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:30,972 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:30,981 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:30,992 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:30,992 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:30,992 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,001 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,011 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,011 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,011 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,021 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,031 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,031 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,031 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,040 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,050 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,051 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,051 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,060 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,069 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,070 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,070 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,081 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,091 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,091 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,092 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,101 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,112 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,113 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,113 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,121 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,131 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,132 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,132 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,142 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,152 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,152 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,153 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,161 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,172 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,172 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)
2014-08-07 14:25:31,172 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 48, in create
    self._delegate_tools.slice_name_check(fields.get('SLICE_NAME')) #Specific check for slice name restrictionas
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 305, in slice_name_check
    raise GFedv2ArgumentError('SLICE_NAME field must be <= 19 characters, must only contain alphanumeric '
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (SLICE_NAME field must be <= 19 characters, must only contain alphanumeric characters or hyphens and those hyphens must not be leading.)

2014-08-07 14:25:31,180 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,190 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,190 [ERROR] - [gsarpc] [SERVER_ERROR] An error in the client/server connection (must be string or read-only buffer, not list)
2014-08-07 14:25:31,190 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 49, in create
    return self._slice_authority_resource_manager.create_slice(certificate, credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/osliceauthorityrm/osliceauthorityresourcemanager.py", line 119, in create_slice
    root = ET.fromstring(credentials)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1641, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not list

2014-08-07 14:25:31,198 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,199 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Field {SLICE_NAME : True} is not of type STRING)
2014-08-07 14:25:31,199 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 47, in create
    self._delegate_tools.object_consistency_check(type_, fields)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 373, in object_consistency_check
    raise GFedv2ArgumentError('Field {' + key + ' : ' + str(value) + '} is not of type ' + field_type)
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Field {SLICE_NAME : True} is not of type STRING)

2014-08-07 14:25:31,206 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,215 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,216 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Member key to modify not of required type. Offending key is: PROJECT_MEMBER. Should be one of these types: ['SLICE_MEMBER', 'SLICE_ROLE'])
2014-08-07 14:25:31,216 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 122, in modify_membership
    result = self._delegate.modify_membership(type_, urn, self.requestCertificate(), credentials, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 158, in modify_membership
    self._delegate_tools.member_check(['SLICE_MEMBER', 'SLICE_ROLE'],options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 295, in member_check
    str(required_field_keys))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Member key to modify not of required type. Offending key is: PROJECT_MEMBER. Should be one of these types: ['SLICE_MEMBER', 'SLICE_ROLE'])

2014-08-07 14:25:31,224 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,236 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:25:31,245 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,254 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:25:31,263 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,272 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,281 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:25:31,289 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,298 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:25:31,307 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,325 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:25:31,336 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,347 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:25:31,358 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,367 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:25:31,377 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,388 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:25:31,397 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,409 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,409 [ERROR] - [gsarpc] [SERVER_ERROR] An error in the client/server connection (must be string or read-only buffer, not list)
2014-08-07 14:25:31,410 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 63, in create
    result = self._delegate.create(type_, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 49, in create
    return self._slice_authority_resource_manager.create_slice(certificate, credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/osliceauthorityrm/osliceauthorityresourcemanager.py", line 119, in create_slice
    root = ET.fromstring(credentials)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1641, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not list

2014-08-07 14:25:31,421 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,433 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:25:31,447 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,457 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:25:31,466 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,477 [INFO] - [gsarpc] Called: <lookup_members>
2014-08-07 14:25:31,487 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,496 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:25:31,507 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,517 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:25:31,527 [INFO] - [gsarpc] Called: <modify_membership>
2014-08-07 14:25:31,542 [INFO] - [gsarpc] Called: <lookup_for_member>
2014-08-07 14:25:31,554 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,568 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:25:31,581 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,596 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:25:31,616 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,635 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,659 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:25:31,661 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Invalid expiry date for object type: PROJECT)
2014-08-07 14:25:31,661 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 79, in update
    result = self._delegate.update(type_, urn, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 105, in update
    raise gfed_ex.GFedv2ArgumentError("Invalid expiry date for object type: " + str(type_))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Invalid expiry date for object type: PROJECT)

2014-08-07 14:25:31,673 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:25:31,687 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:25:31,698 [INFO] - [gsarpc] Called: <create>
2014-08-07 14:25:31,716 [INFO] - [gsarpc] Called: <update>
2014-08-07 14:25:31,717 [ERROR] - [gsarpc] [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when updating an object : PROJECT_NAME)
2014-08-07 14:25:31,717 [ERROR] - [gsarpc] Traceback (most recent call last):
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedrpc2/fedrpctwo/gsavtwo.py", line 79, in update
    result = self._delegate.update(type_, urn, self.requestCertificate(), credentials, fields, options)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/ofed2/osavtwodelegate.py", line 107, in update
    self._delegate_tools.object_update_check(fields, self._project_whitelist)
  File "/home/umar.toseef/ALIEN/C-BAS/Ohouse/src/plugins/fedtools/delegatetools.py", line 346, in object_update_check
    raise GFedv2ArgumentError('Cannot pass the following key(s) when updating an object : ' + ', '.join(whitelist))
GFedv2ArgumentError: [ARGUMENT_ERROR] The arguments provided to the call were mal-formed or mutually inconsistent. (Cannot pass the following key(s) when updating an object : PROJECT_NAME)

2014-08-07 14:25:31,727 [INFO] - [gsarpc] Called: <delete>
2014-08-07 14:25:31,737 [INFO] - [gsarpc] Called: <lookup>
2014-08-07 14:44:04,770 [INFO] - Logging initialized
2014-08-07 14:44:04,785 [INFO] - [pluginmanager] loading mailer
2014-08-07 14:44:04,903 [INFO] - [pluginmanager] registering service mailer
2014-08-07 14:44:04,903 [INFO] - [pluginmanager] loading mongodb
2014-08-07 14:44:05,205 [INFO] - [pluginmanager] registering service mongodb
2014-08-07 14:44:05,205 [INFO] - [pluginmanager] loading configdb
2014-08-07 14:44:06,201 [INFO] - [pluginmanager] registering service config
2014-08-07 14:44:06,201 [INFO] - [pluginmanager] registering service configexceptions
2014-08-07 14:44:06,201 [INFO] - [pluginmanager] loading schedule
2014-08-07 14:44:06,225 [INFO] - [pluginmanager] registering service schedule
2014-08-07 14:44:06,225 [INFO] - [pluginmanager] registering service scheduleexceptions
2014-08-07 14:44:06,225 [INFO] - [pluginmanager] loading fedtools
2014-08-07 14:44:06,451 [INFO] - [pluginmanager] registering service apiexceptionsv1
2014-08-07 14:44:06,451 [INFO] - [pluginmanager] registering service apiexceptionsv2
2014-08-07 14:44:06,452 [INFO] - [pluginmanager] registering service apitools
2014-08-07 14:44:06,452 [INFO] - [pluginmanager] registering service resourcemanagertools
2014-08-07 14:44:06,479 [INFO] - [pluginmanager] registering service delegatetools
2014-08-07 14:44:06,480 [INFO] - [pluginmanager] loading oregistryrm
2014-08-07 14:44:06,482 [INFO] - [pluginmanager] registering service oregistryrm
2014-08-07 14:44:06,482 [INFO] - [pluginmanager] registering service oregistryexceptions
2014-08-07 14:44:06,482 [INFO] - [pluginmanager] loading osliceauthorityrm
2014-08-07 14:44:06,508 [INFO] - [pluginmanager] registering service osliceauthorityrm
2014-08-07 14:44:06,509 [INFO] - [pluginmanager] registering service osliceauthorityexceptions
2014-08-07 14:44:06,509 [INFO] - [pluginmanager] loading worker
2014-08-07 14:44:06,528 [INFO] - [pluginmanager] registering service worker
2014-08-07 14:44:06,529 [INFO] - [pluginmanager] loading flaskrpcs
